### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JOHAE96** [Daphne1/Chatroom#3]
- [x] räume löschen
- [x] bannen ?
- [x] mehrfach anmeldungen verhindern
- [x] falsches passwort
- [x] gui aktualisieren

**Comment by JOHAE96** [comment]
falsches passwort sollte abgelehnt werden

- [ ] client thread richtige beender ( aus nutzerliste enfernen)
- [ ] json objekte statt einfachen string senden

**Comment by JOHAE96** [comment]
BufferedWriter output = new BufferedWriter(new FileWriter(fileName, true));
            output.append(msg);
